name: Commands Workflow

on: push

jobs:
  testing-ubunto-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: check all environment variables
        run: env
      - name: check directory
        run: |
          pwd
          ls
      - name: check directory in a different way
        run: >
          echo ------------------------------\n
          &&
          pwd
          &&
          ls
      - name: check all environment variables in sh instead of bash
        run: env
        shell: sh
  testing-windows-cmd:
    runs-on: windows-latest
    needs: testing-ubunto-cmd
    steps:
      - name: check with powershell
        run: dir
      - name: check with bash in windows
        shell: bash
        run: ls


