name: test Actions

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple js action that takes input
        id: greet-me
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Bnaji
      - name: check greeting time
        run: echo ${{ steps.gree-me.outputs.time }}